### ISSUE TITLE
Object is not iterable when uploading source maps

### ISSUE THREAD

**Issue by RobbieZhaoPayPal** [DataDog/datadog-ci#1375]
### Bug description

When I use this command to upload the source maps
```
npx datadog-ci sourcemaps upload <my-folder>       --service=<my-service>      --release-version=<my-version>       --minified-path-prefix=<my-path-prefix>
```
It's erroring out with the following error 
```  
Starting upload with concurrency 20. 
Will look for sourcemaps in <a path>
Will match JS files for errors on files starting with <a path>
version: <a version> service: <my-service> project path: 
Uploading sourcemap <source-map-file> for JS file available at <js-file>
Uploading sourcemap <source-map-file> for JS file available at <js-file>
Type Error: Object is not iterable.
    at __values (<my-path>/node_modules/tslib/tslib.js:226:15)
    at __asyncValues (<my-path>/node_modules/@datadog/datadog-ci/dist/helpers/concurrency.js:14:66)
    at <my-path>/node_modules/@datadog/datadog-ci/dist/helpers/concurrency.js:28:34
    at Generator.next (<anonymous>)
    at <my-path>/node_modules/@datadog/datadog-ci/dist/helpers/concurrency.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (<my-path>/node_modules/@datadog/datadog-ci/dist/helpers/concurrency.js:4:12)
    at doWithMaxConcurrency (<my-path>/node_modules/@datadog/datadog-ci/dist/helpers/concurrency.js:24:64)
    at UploadCommand.<anonymous> (<my-path>/node_modules/@datadog/datadog-ci/dist/commands/sourcemaps/upload.js:179:78)
    at Generator.next (<anonymous>)
```
For context, I am using "@datadog/datadog-ci": "^2.39.0".

### Additional context

- MacOS: Ventura 13.6.7
- Node: v18.19.0

### Command

None

**Comment by Drarig29** [comment]
Hi @RobbieZhaoPayPal! Did this happen multiple times? Can you reproduce it or not?
