### ISSUE TITLE
Error when executing synthetics Multistep API Test

### ISSUE THREAD

**Issue by edslourenco** [DataDog/datadog-ci#177]
**Describe what happened**
When running the synthetic tests of type Multistep API Test, I received the following error.
```
 ERROR 
TypeError: Cannot read property 'method' of undefined
    at renderApiRequestDescription (/var/www/html/project/node_modules/@datadog/datadog-ci/dist/commands/synthetics/renderer.js:115:44)
    at renderResultOutcome (/var/www/html/project/node_modules/@datadog/datadog-ci/dist/commands/synthetics/renderer.js:86:36)
    at renderExecutionResult (/var/www/html/project/node_modules/@datadog/datadog-ci/dist/commands/synthetics/renderer.js:143:27)
    at /var/www/html/project/node_modules/@datadog/datadog-ci/dist/commands/synthetics/renderer.js:177:21
    at Array.map (<anonymous>)
    at Object.renderResults (/var/www/html/project/node_modules/@datadog/datadog-ci/dist/commands/synthetics/renderer.js:177:10)
    at RunTestCommand.<anonymous> (/var/www/html/project/node_modules/@datadog/datadog-ci/dist/commands/synthetics/run-test.js:70:58)
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/html/project/node_modules/@datadog/datadog-ci/dist/commands/synthetics/run-test.js:5:58)
```

Running the synthetic tests of type HTTP Test are successfully performed.

**Steps to reproduce the issue:**
Run the synthetic tests of type multi-step

**Expected behaviour:**
📝

**Actual behaviour:**
📝

**Additional context**
 - OS version: Alpine Linux 3.13.2
 - Node version: v14.16.0
 - an explanation of what might cause the bug and/or how it can be fixed: In synthetic tests of type multi-step, the request does not have the method attribute

**Comment by m-rousse** [comment]
Hi @edslourenco,
Thanks for your report, this is a bug in our result rendering, we will fix it in the coming days.
